پیغام زیر را داد:

(myenv) root@Telegram:~# python3 extend_subscription.py
فیلدهای نام کاربری و رمز عبور پیدا شدند.
ورود ناموفق بود. عنوان صفحه: 37.27.253.117-Overview
پیام خطایی یافت نشد.
اسکرین‌شات از صفحه گرفته شد: /root/login_page.png
(myenv) root@Telegram:~#

ولی در اسکرین شاتی که گرفته توانسته وارد پنل بشود و اسکرین شاتی که فرستاده از صفحه زیر است:
http://37.27.253.117:2095/panel/
حالا در گام بعدی باید به آدرس زیر برود:
http://37.27.253.117:2095/panel/inbounds